language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python-sphinx
      - libelf-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.16.54
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=3.16.54 DPDK=1
  - KERNEL=3.16.54 DPDK=1 OPTS="--enable-shared"
  - KERNEL=4.15.3
  - KERNEL=4.14.19
  - KERNEL=4.9.81
  - KERNEL=4.4.115
  - KERNEL=4.1.49
  - KERNEL=3.10.108
  - TESTSUITE=1 LIBS=-ljemalloc

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
