language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - python-sphinx

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.16.46
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=3.16.46 DPDK=1
  - KERNEL=3.16.46 DPDK=1 OPTS="--enable-shared"
  - KERNEL=4.12.2
  - KERNEL=4.11.11
  - KERNEL=4.9.38
  - KERNEL=4.4.77
  - KERNEL=4.1.42
  - KERNEL=3.10.107
  - TESTSUITE=1 LIBS=-ljemalloc

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - ovs-build@openvswitch.org
